#!/usr/bin/env bash
# =============================================================================
#  scripts/latlon_to_hex.sh  —  Compute hex (q, r) from city lat/lon in DB
#
#  Reads latitude + longitude directly from p3_cities (already inserted by
#  seed.sql), runs the pointy-top axial projection in awk, then writes q and r
#  back to the DB.  No coordinates are hardcoded here.
#
#  Projection constants (reverse-engineered from the Hanseatic city cluster):
#    Anchor : Lübeck  53.8655°N  10.6866°E  →  hex (0, 0)
#    HEX_SIZE   = 0.55  (degrees of latitude per hex radius, ≈ 50 nm)
#    COS_LAT_DEG= 53.0  (central latitude for E/W cosine correction)
#
#  r (latitude axis) is geographically accurate to ±1 hex.
#  q (longitude axis) is accurate for the Baltic cluster; Atlantic and
#  Mediterranean cities may be off by 1-3 hexes — adjust manually if needed.
#
#  Usage
#  ──────
#    ./latlon_to_hex.sh                        # apply to DB (default)
#    ./latlon_to_hex.sh --dry-run              # print SQL without applying
#    ./latlon_to_hex.sh --csv                  # print name,q,r,lat,lon to stdout
#
#  Environment (inherits from app.sh, or set manually)
#    P3_USER   postgres user  (default: postgres)
#    P3_DB     database name  (default: traderdude)
# =============================================================================

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Config ─────────────────────────────────────────────────────────────────────
P3_USER="${P3_USER:-postgres}"
P3_DB="${P3_DB:-traderdude}"

readonly ANCHOR_LAT=53.8655
readonly ANCHOR_LON=10.6866
readonly HEX_SIZE=0.55
readonly COS_LAT_DEG=53.0

# ── Fetch cities from DB ───────────────────────────────────────────────────────
fetch_cities() {
    psql -X -t -A --field-separator='|' \
        --username="$P3_USER" --dbname="$P3_DB" \
        --command="SELECT name, latitude, longitude
                     FROM p3_cities
                    WHERE latitude IS NOT NULL
                      AND longitude IS NOT NULL
                    ORDER BY name;"
}

# ── Core projection (awk) ──────────────────────────────────────────────────────
compute_hex() {
    # stdin:  name|lat|lon
    # stdout: name|q|r|lat|lon
    local cos_lat
    cos_lat=$(awk -v d="$COS_LAT_DEG" \
        'BEGIN { printf "%.10f", cos(d * 3.141592653589793 / 180) }')

    awk -v alat="$ANCHOR_LAT" -v alon="$ANCHOR_LON" \
        -v coslat="$cos_lat"  -v size="$HEX_SIZE"   \
        -F'|' '
    {
        name = $1; lat = $2; lon = $3

        # lat/lon delta → flat x, y  (y positive = south)
        y = alat - lat
        x = (lon - alon) * coslat

        # flat x,y → fractional axial  (pointy-top hex)
        fq = (sqrt(3)/3 * x - 1.0/3 * y) / size
        fr = (2.0/3 * y) / size

        # axial → cube
        cx = fq; cz = fr; cy = -cx - cz

        # cube rounding  (Red Blob Games)
        rx = int(cx + (cx >= 0 ? 0.5 : -0.5))
        ry = int(cy + (cy >= 0 ? 0.5 : -0.5))
        rz = int(cz + (cz >= 0 ? 0.5 : -0.5))
        dx = (rx-cx); if (dx < 0) dx = -dx
        dy = (ry-cy); if (dy < 0) dy = -dy
        dz = (rz-cz); if (dz < 0) dz = -dz
        if      (dx > dy && dx > dz) rx = -ry - rz
        else if (dy > dz)            ry = -rx - rz
        else                         rz = -rx - ry

        q = rx; r = rz
        printf "%s|%d|%d|%s|%s\n", name, q, r, lat, lon
    }'
}

# ── Build SQL ──────────────────────────────────────────────────────────────────
build_sql() {
    # stdin: lines of name|q|r|lat|lon
    # stdout: SQL to UPDATE p3_cities then bootstrap p3_hex_tiles
    local rows=()
    while IFS='|' read -r name q r lat lon; do
        rows+=("    ('$name', $q, $r)")
    done

    cat <<SQL
-- Auto-generated by scripts/latlon_to_hex.sh
-- Anchor: Lübeck ($ANCHOR_LAT, $ANCHOR_LON) = hex (0,0)
-- HEX_SIZE=$HEX_SIZE  COS_LAT_DEG=$COS_LAT_DEG

WITH city_coords (city_name, q, r) AS (VALUES
$(IFS=,$'\n'; printf '%s\n' "${rows[*]}")
)
UPDATE p3_cities ci
   SET hex_q = cc.q,
       hex_r = cc.r
  FROM city_coords cc
 WHERE ci.name = cc.city_name;

-- Bootstrap p3_hex_tiles for every city hex
INSERT INTO p3_hex_tiles (q, r, terrain, city_id)
SELECT
    ci.hex_q,
    ci.hex_r,
    CASE WHEN ci.name IN (
        'Novgorod', 'Groningen', 'Bremen', 'Cologne', 'Torun', 'Ladoga',
        'Constantinople', 'Alexandria', 'Tunis'
    ) THEN 'land' ELSE 'coast' END,
    ci.city_id
FROM p3_cities ci
WHERE ci.hex_q IS NOT NULL
ON CONFLICT (q, r) DO UPDATE
    SET city_id = EXCLUDED.city_id,
        terrain  = EXCLUDED.terrain;
SQL
}

# ── Main ───────────────────────────────────────────────────────────────────────
MODE="${1:---apply}"

RAW="$(fetch_cities)"
if [[ -z "$RAW" ]]; then
    echo "ERROR: No cities found in p3_cities. Has seed.sql been applied?" >&2
    exit 1
fi

COMPUTED="$(echo "$RAW" | compute_hex)"

case "$MODE" in
    --csv)
        echo "name,q,r,lat,lon"
        echo "$COMPUTED" | awk -F'|' '{print $1","$2","$3","$4","$5}'
        ;;
    --dry-run)
        echo "$COMPUTED" | build_sql
        ;;
    --apply | *)
        SQL="$(echo "$COMPUTED" | build_sql)"
        echo "$SQL" | psql -X \
            --username="$P3_USER" --dbname="$P3_DB" >/dev/null \
        && echo "Hex coordinates applied ($(echo "$COMPUTED" | wc -l | tr -d ' ') cities)." \
        || { echo "ERROR: psql failed." >&2; exit 1; }
        ;;
esac
